### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by Perlence** [tbug/aiochannel#1]
As Rob Pike [once said](https://youtu.be/VoS7DsT1rdM?t=38m49s), "If you don't have `select`, you don't have real concurrency."

Is it possible to implement `select` for aiochanels? There is an [implementation](https://github.com/stuglaser/pychan) of select for threading-based channels with API similar to Unix select, where you pass a list of consumers and producers and receive a channel and a value. It gets the job done, but feels a bit clunky maybe.

I'm willing to try to implement it, if you're OK with this approach.

**Comment by tudborg** [comment]
You can get select-like behaviour just by using the `asyncio` stdlib. `wait` is your friend here.

But a more abstract `select()` would be useful.

Using the approach from the linked page is probably the wrong way to go about it though.
Threading-based channels have issues that we don't need to think about.
A select for `Channel` (which in fact could be made to work for any list of futures, see first example) would be much much simpler. No locking required, etc.

I think it would be fairly easy to build on top of `asyncio.wait()`.
I'm not a 100% sure on how to handle channels closing,
and if using`wait` and then cancelling the `pending` ones when a `done` future is returned, or
if it would make more sense to let the select be a more specialised class that holds state and is only for Channels. 

One option would be to do something like:

``` python

from aiochannel import aioselect, Channel, ChannelClosed

c1 = Channel()
c2 = Channel()
c3 = Channel()
# ...
async def main():
    channels = [c1, c2, c3]
    while len(channels) > 0:
        try:
            (channel, value) = await aioselect(channels, timeout=5.0)
        except ChannelClosed:
            # one of the channels have been closed
            channels = filter(lambda c: not c.is_closed(), channels)
        do_work(channel, value)
    # all channels closed here (or timeout)
```

alternatively, a `Channel`-only select could handle close events internally

``` python

from aiochannel import Channel, ChannelClosed

c1 = Channel()
c2 = Channel()
c3 = Channel()

# ...

async def main():
    channels = [c1, c2, c3]
    # The timeout is for the entire block
    async with Channel.select(channels, timeout=5.0) as selector:
        while not selector.closed(): # a selector will close when all channels are closed
            (channel, value) = await selector(timeout=1.0) # timeout for individual items
            do_work(channel, value)
    # all channels are closed here (or timeout)
```

Both of the above examples should probably thow a `TimeoutError` on timeout.

The first example doesn't really save much code and is error-prone. It will probably also perform worse then example two, where we can hide a bunch of cleverness in the async context manager.

So I think the second approach would be a good candidate.
Thoughts?

**Comment by Perlence** [comment]
I didn't check the actual implementation of chanselect and its thread-related semantics, but I like the general approach, when you pass getters and putters, and get channel that's ready.

The use of context here looks promising. Though the arguments of select must be operations (get/put) on channels, not just channels.

There's also [another attempt](https://github.com/rgalanakis/goless) at bringing Go-like functionality to Python. They took [`reflect.Select`](https://golang.org/pkg/reflect/#Select) for reference and implemented it in Python.

I tried to convert an [example](https://golang.org/ref/spec#Select_statements) from golang specification:

``` python
c = Channel()
c1 = Channel()
c2 = Channel()
c3 = Channel()
i1, i2 = 0, 0

ch, value, ok = await select(c1.get(), c2.put(i2), c3.get())
if ch is c1:
    i1 = value
    print("received", i1, "from c1")
elif ch is c2:
    print("sent", i2, "to c2")
elif ch is c3:
    i3 = value
    if ok:
        print("received", i3, "from c3")
    else:
        print("c3 is closed")
else:
    print("no communication")
```

Methods `get()` and `put(v)` return Future subclasses that hold references to corresponding channels. Select must raise an error if _c2_ has been closed prior, Go program panics in this case. _ch_ is None when no channel are ready, i.e. default case, _value_ is result of `get()`, _ok_ is True when an actual value was received from channel, _ok_ is False when channel was closed.

Docs of `reflect.Select` state that _ok_ is "a boolean indicating whether the value corresponds to a send on the channel (as opposed to a zero value received because the channel is closed)." I'm very ashamed, but I don't quite get this passage :smile:

**Comment by tudborg** [comment]
Ah, I misunderstood what functionality you'd like from a select. :smiley: 
I thought your use case was channel fan-in.

I'm not very fond of just grabbing some other language' implementation and writing it in python.
It's usually suboptimal (and not very pythonic).

Could you explain the use case. I don't understand where it's practical :sweat_smile: 

When would you use:

``` python
ch, value, ok = await select(c1.get(), c2.put(i2), c3.get())
```

and what does it provide over:

``` python
done, pending = await asyncio.wait([c1.get(), c2.put(i2), c3.get()], return_when=asyncio.FIRST_COMPLETED)
[p.cancel() for p in pending]
```

Do you have a specific use case in mind where you need this?

**Comment by Perlence** [comment]
Yes, using `asyncio.wait` like you've shown totally does most of the work. But I'd also like to get the channel from which the value was received. Here's an example using infinite producer and a quit channel:

``` python
async def main():
    out = Channel()
    quit = Channel()
    asyncio.ensure_future(producer(out, quit))

    for _ in range(3):
        value = await out.get()
        print('got', value, 'from producer')

    quit.close()

async def producer(out, quit):
    i = 0
    while True:
        ch, value = select(out.put(i), quit.get())
        if ch is quit and ch.closed():
            # Time to quit
            out.close()
            break
        elif ch is out:
            # We've just put *i* into channel, let's increase it for
            # next iteration
            i += 1
```

So, I want to use select to put value into _out_ channel and check if _quit_ channel was closed elsewhere at the same time. Also I figured out that _ok_ value from select is redundant, I can just check if _ch_ was closed.

**Comment by tudborg** [comment]
Working example without the `select` implementation:

``` python
async def main():
    out = Channel()
    stop = asyncio.Event()
    asyncio.ensure_future(producer(out, stop))
    for _ in range(3):
        print("from out: {}".format(await out.get()))
    stop.set()

async def producer(out, stop):
    i = 0
    while not stop.is_set():
        done, pending = await asyncio.wait([stop.wait(), out.put(i)], return_when=asyncio.FIRST_COMPLETED)
        [p.cancel() for p in pending]
        if stop.is_set():
            out.close()
            break
        else:
            i += 1

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

I don't undertand why you'd need the channel returned to you :confused:
It would be super rad if you could give an example where the returned channel is the best way to solve a specific problem :)
It seems like you can solve the problem just as easily and readable using the standard library.

The reason I'm uncomfortable with this change, is that I only see two solutions for implementing `select` in the currently discussed form:
- `Channel` needs a breaking change where `put()` and `get()` also returns their own channel
- `Future` returned by `get()` and `put()` needs to hack a reference to the channel onto the `Future`

I don't want to break backwards compat, and I _really_ don't want to hack `Future`.

If you can come up with a way that doesn't break backwards compat or hacks values onto stdlib objects, I'd be a lot more open to adding some kind of `select` functionality.

Sorry for being difficult :smile:

**Comment by Perlence** [comment]
Valid point, this particular case can be implemented with Event. Let's see if I can come up with better example :smile:

**Comment by Perlence** [comment]
Well, select is used mostly for timeouts and quit channels in Go.

Here's another example, as contrived as it can be. Let's introduce a control channel that changes the state of running coroutine:

``` python
async def main():
    nums = Channel()
    control = Channel()
    out = Channel()

    asyncio.ensure_future(mul(nums, control, out))

    await nums.put(4)
    print('got', await out.get())  # must be 8
    await control.put(3)
    await nums.put(4)
    print('got', await out.get())  # must be 12

    nums.close()
    control.close()
    await out.join()


async def mul(numbers, control, out):
    multiplier = 2
    while True:
        ch, value = await select(numbers.get(), control.get())
        if ch.closed():
            out.close()
            return
        elif ch is numbers:
            await out.put(value * multiplier)
        elif ch is control:
            multiplier = value
```

I assume, that we can otherwise make `mul` a class and modify multiplier directly since this particular operation is synchronous. But if the procedure that handles messages from control channel is asynchronous then we must put a lock on it and on `await out.put(value * multiplier)` to eliminate the data race.

As for implementation, if we stick with current form of select, we can subclass the Future:

``` python
class Channel(object):
    ...

    @coroutine
    def _put_wait(self, item):
        while self.full() and not self._close.is_set():
            ...
        return self.put_nowait(item)

    def _link_futures(self, chan_fut, task):
        exc = task.exception()
        if exc is not None:
            chan_fut.set_exception(exc)
        else:
            chan_fut.set_result(task.result())

    def put(self, item):
        chan_fut = ChannelFuture(self, loop=self._loop)
        task = self._loop.create_task(self._put_wait(item))
        task.add_done_callback(functools.partial(self._link_futures, chan_fut))
        return chan_fut


class ChannelFuture(Future):
    def __init__(self, channel, *, loop=None):
        super().__init__(loop=loop)
        self.channel = channel
```

It still looks scary, chained futures meh, but at least we don't assign any arbitrary attributes to asyncio.Future.

On other hand, we can introduce methods `Channel.get_case()`, and `Channel.put_case(item)`  specifically for use in select:

``` python
await select(ch1.get_case(), ch2.put_case('item'))
```

Or do it the most simple way, as it's done in pychan: 

``` python
await select([ch1], [(ch2, 'item')])
```

**Comment by tudborg** [comment]
Okay, so I gave this some thought.

Sub-classing future seems wrong to me.
Adding new functions for the select behavior makes more sense then touching the existing ones, but again, there is really no need for it to be in the channel itself.

And i still don't understand the actual need for the channel to be returned.
You'd need to inspect the returned `ch` from a select before you'd know what could
even be in the second part of the returned tuple. Either a response from put or a response from get.
It all seems very non-pythonic.

`aiochannel` is pretty much _just_ a "closable queue", and I don't want to add too many extras.

That said, wrapping the behavior in an external module should be fairly easy.
You can build select-like behavior without touching the `aiochannel` package at all.
Cancelling a pending `get()` or `put()` future should prevent it from happening (given that it is not already `completed()` ofc :smile:)

Your pychan example could be implemented that way:

``` python
await select([ch1], [(ch2, 'item')])
```

I'd be okay with merging something like that as a separate module, so it would be used something like

``` python
from aiochannel import Channel, select
ch1 = Channel()
ch2 = Channel()

ch, val = await select([ch1], [(ch2, "item")])
```

**Comment by Perlence** [comment]
Check this out, they say that current implementation of async/await overuses exceptions. Well, consider this!

``` python
async def mul(numbers, control, out):
    multiplier = 2
    while True:
        try:
            await select([numbers, control], [])
        except ChannelClosed:
            out.close()
            return
        except numbers.received as value:
            await out.put(value * multiplier)
        except control.received as new_mult:
            multiplier = new_mul
```

Yeh, I just don't know when stop.

**Comment by tudborg** [comment]
No worries, I don't mind discussing it at all :)

That would work as well, but using exceptions as control flow like that is probably a Bad Idea :tm: and the way values are passed is really messy :smile:
But at least it _looks_ better :smile:

Ideally I'd like to avoid encouraging `while True:` blocks, and using exceptions for control flow :smile:

what about:

**example 1**

``` python
async def mul(numbers, control, out):
    multiplier = 2
    while not out.closed():
        try:
            async with select(get=[numbers, control]) as (channel, value):
                if channel is control:
                    multiplier = value
                elif channel is numbers:
                    await out.put(value * multiplier)
                else:
                    raise RuntimeError("Invalid channel")
        except ChannelClosed:
            out.close()
```

The `select` takes kwargs with function names, calls those functions, and expect futures in return.
When a future yields, the async with block is run, and you have access to the channel and value in that block.

We probably don't need the `async with`. The `select` could return an async iterator:

**example 2**

``` python
async def mul(numbers, control, out):
    multiplier = 2
    while not out.closed():
        try:
            async for (channel, value) in select(get=[numbers, control]):
                if channel is control:
                    multiplier = value
                elif channel is numbers:
                    await out.put(value * multiplier)
                else:
                    raise RuntimeError("Invalid channel")
        except ChannelClosed:
            out.close()
```

Now, the `try/catch` makes this code look silly.
One option would be to go back to the whole "returning a closed state"

**example 3**

``` python
async def mul(numbers, control, out):
    multiplier = 2
    async for (channel, value, closed) in select(get=[numbers, control]):
        if closed: # `channel` closed, we don't care about which channel
            break
        elif channel is control:
            multiplier = value
        elif channel is numbers:
            await out.put(value * multiplier)
        else:
            raise RuntimeError("Unhandled case")
```

Or even implicitly just breaking the loop when a channel closes, and then handling
things in the `for`'s `else` block.
This is probably the most pythonic of the examples.

**example 4**

``` python
async def mul(numbers, control, out):
    multiplier = 2
    async for (channel, value) in select(get=[numbers, control]):
        elif channel is control:
            multiplier = value
        elif channel is numbers:
            await out.put(value * multiplier)
        else:
            raise RuntimeError("Unhandled case")
    else:
        if numbers.closed():
            print ("numbers closed")
        elif control.closed():
            print("control closed")
```

I like that in the last examples the select is an async iterator.
Handling channel close internally in the async loop might be impractical for some use cases,
but for the current one it seems to make sense.

---

I guess I'm working with two different versions of select-like behaviour.
- The high-level pythonic (and pretty :heart_eyes: ) API version, something like an async iterator, or similar.
- The low-level version similar to `select.select` ( https://docs.python.org/3/library/select.html#select.select )

**Comment by Perlence** [comment]
I really like the third example, it looks very nice, bravo. The `for / select` construct is not the only use case of `select`, but certainly the most used one. What if there were two versions of select: the one that returns async iterator as shown in example 3 and 4 (maybe call it `iterselect`), and plain select returning `(channel, value, closed)` tuple.

**Comment by tudborg** [comment]
I've been super busy with the day job, but I'll give this a look soon-ish.
I think I agree that the most logical approach is to have some kind of low-level select, and then build a nicer high-level common-usecase API with that.
I'll get back to this issue in a few days :)

**Comment by tudborg** [comment]
Okay, so as I started looking into how to actually implement this, I started to discover a few things that would make it strange to work with.
1. You'd have no control over how many futures would complete before control is returned to your `select` code block, which is weird compared to how you'd normally use `select` in other languages (or even python's own `select()`. So a low-level function that is supposed to return when _the first_ futures completes seems impossible without touching internals.
2. As you are not asking for what is _ready_ (as with the normal select) but what _completed_, you wouldn't be able to just not care what happened to the remaining tasks. It would be a mess of weird corner cases.
3. I then tried to work out if it would make sense to do it like a normal select (to tell you when something is _ready_ for a write or a read) but that would require hooking in to the existing waiters (the pending putters and getters), which could mess up the queue if the external handler does something bad.

So, it doesn't seem like using the existing async interface is a good way to provide this functionality.

I think the best way to get something select-like would be to hook into the existing waiters, I'll just have to think of a way to do this without making it super easy to break a queue by binding a bad handler.

Oh, and the previous scenario we were toying with can easily solved like this instead:

(full working example)

``` python
import asyncio
from aiochannel import Channel


async def work(numbers, control, out):
    # work's shared context
    class Context(object):
        multiplier = 0

    # how to handle control data
    async def handle_control(ctx):
        async for n in control:
            print("control: {}".format(n))
            ctx.multiplier = n
        numbers.close()

    # how to handle number data
    async def handle_number(ctx):
        async for n in numbers:
            print("number:  {} * {}".format(n, ctx.multiplier))
            value = ctx.multiplier * n
            await out.put(value)
        control.close()

    # create shared context
    context = Context()
    # wait for jobs to complete
    await asyncio.wait([handle_control(context), handle_number(context)])
    # close out channel
    out.close()


async def main(loop):
    numbers = Channel()
    control = Channel()
    out = Channel()

    # demo data
    async def number_adder():
        for i in range(20):
            await asyncio.sleep(0.05)
            await numbers.put(i)
        numbers.close()

    async def control_adder():
        for i in range(1, 4):
            await asyncio.sleep(0.2)
            await control.put(i)

    asyncio.ensure_future(number_adder())
    asyncio.ensure_future(control_adder())


    # wait for the work to be done
    await work(numbers, control, out)

    # and print the channel's internal queue 
    print(list(out._queue))


loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
loop.close()
```

which is actually about the same size as the other examples, and I think it reads better.
