### ISSUE TITLE
InvalidStateError during close

### ISSUE THREAD

**Issue by stijn-devriendt** [tbug/aiochannel#3]
Hi Henrik,

We're running into an issue where InvalidStateError is raised during close().
Tracking it down we find that 49b04cded88bb5f2c62a665f44e9e528b78efa27 is needed. However, it was reverted at 61c8f2535e15b8ad96deb3a50ef7819b5f32ccc4.

We're currently running an older version for a while now to work around this issue.

I believe the use-case is that a put/get operation is cancelled (e.g. using `asyncio.wait(channel.get(some_value), timeout=10)`).
In that case, the put()/get() function doesn't remove the future from the deque, but merely marks it cancelled.
`_wakeup_next` dodges this behavior by checking if the future is done, but `close` no longer does this.

Let me know if you need more info. I'll be unavailable for 2 weeks, but will respond when I get back.

Best regards,
Stijn

**Comment by tudborg** [comment]
Hey Stijn.
I've had a long break from github, sorry for not seeing your issue.

Did you ever manage to make a small sample to reproduce this bug?
Would be helpful with a snippet so I can reproduce it.

**Comment by stijn-devriendt** [comment]
Hi Henrik,

Thanks for getting back.

I think the example below should do:
```python
from aiochannel import Channel
import asyncio


async def reproduce():
    c = Channel(3)

    getter_task = asyncio.create_task(c.get())
    await asyncio.sleep(0.1)
    getter_task.cancel()

    print("closing")
    c.close()
    print("closed")

asyncio.run(reproduce())
```
displays:
```
closing
Traceback (most recent call last):
  File "/home/sde/.config/JetBrains/PyCharmCE2021.3/scratches/aiochannel_issue.py", line 16, in <module>
    asyncio.run(reproduce())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/sde/.config/JetBrains/PyCharmCE2021.3/scratches/aiochannel_issue.py", line 13, in reproduce
    c.close()
  File "/home/sde/projects/lynx/components/lynxathome/lah-node/venv/lib/python3.7/site-packages/aiochannel/channel.py", line 172, in close
    getter.set_exception(ChannelClosed())
asyncio.base_futures.InvalidStateError: invalid state
```

Regards,
Stijn

**Comment by tudborg** [comment]
Thank you so much Stijn, that's very helpful.
I'll have a look as soon as I can :)

**Comment by tudborg** [comment]
I had made a bad assumption that the Futures I use internally to wait for the channel to be ready could be cancelled externally.

In PR #10 I've accounted for cancelled futures on close, which should not simply ignore those (since they are already canceled)

Do you think this would solve your issue?

**Comment by stijn-devriendt** [comment]
I'd say the solution looks good to me. I considered whether there are other possibilities for set_exception to fail (iow the future is already done()), but that can only happen if the queue's invariant of atomic pop() fails.

Thanks!
