### ISSUE TITLE
aiochannel doesn't install in  windows

### ISSUE THREAD

**Issue by Lucas-Brum** [tbug/aiochannel#5]
Hi, i'm to install  aiochannel on my windows 10 64 bits

![image](https://user-images.githubusercontent.com/17210254/151970415-7f055437-2ecb-4154-ad88-c2a620c554d3.png)

**Comment by tudborg** [comment]
Hey Lucas.
Seems like a problem with the package' LONG_DESCRIPTION.
I read in the entire README.md file in `setup.py`.

Windows support isn't a priority for me right now, but feel free to make PR if you manage to fix it :)

**Comment by tudborg** [comment]
I checked what character was at position 412, and it was a `”`. I've changed that to `"` in the hopes that that will solve it for you. Try giving it a look.

**Comment by tudborg** [comment]
A new version has been published to pypi which contains the character changes I made.

Feel free to reopen this issue if it does not solve your problem.

**Comment by Lucas-Brum** [comment]
I found that the error was my Python version which was 3.9 and needed to be 3.7, thanks for try help me anyway
